default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: postgis
  postgis_schema: public
  schema_search_path: public,postgis
  pool: 5

development:
  <<: *default
  database: cases

test:
  <<: *default
  database: cases_test