# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2bcf5ff26dac68346fd17f229abe0e1d2d5595b026c1a4faad1c318f6c3b6533a67b5d44f27100795f745ab163d26de104407e17a979542b71f11c37489a6be

test:
  secret_key_base: ce9d69080b512febf1cf74bd10f71d2e89c73f784b322d5fbc8658bc538ac52847aa0ce094b43e4ee35eb8c06be6dd9b6f1bf8dd2917b30b0ab7970be16d2d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
